gccA:
	gcc -Wall 1_A.c
d_gccA:	
	gcc -Wall -DDEBUG 1_A.c
gccB:
	gcc -Wall 1_B.c
d_gccB:	
	gcc -Wall -DDEBUG 1_B.c
exe1:
	./a.out < 1_input.txt
gcc:
	gcc -Wall 2.c
dgcc:
	gcc -Wall -DDEBUG 2.c
exe:
	./a.out < input_2.txt
